---
# Don't build an IPA deployment image, instead download upstream images.
create_ipa_image: false
download_ipa: true

# Use a locally hosted CentOS8 cloud image.
use_cirros: true
cirros_deploy_image_upstream_url: "https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud.latest.x86_64.qcow2"
